{
  parserClass="org.logoce.lmf.editor.parser.LMParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="LMF"
  psiPackage="org.logoce.lmf.editor.psi"
  psiImplPackage="org.logoce.lmf.editor.psi.impl"

  elementTypeClass="org.logoce.lmf.editor.psi.LMElementType"
  tokenTypeClass="org.logoce.lmf.editor.psi.LMTokenType"
  elementTypeHolderClass="org.logoce.lmf.editor.psi.LMTokenTypes"

  tokens = [
    TYPE = 'TYPE'
    VALUE = 'VALUE'
    LIST_SEPARATOR = 'LIST_SEPARATOR'
    WHITE_SPACE = 'WHITE_SPACE'
    OPEN_NODE = 'OPEN_NODE'
    CLOSE_NODE = 'CLOSE_NODE'
    NAME = 'NAME'
    QUOTE = 'QUOTE'
    ASSIGN = 'ASSIGN'
  ]
}

lmFile ::= element*

element ::= OPEN_NODE TYPE (word | WHITE_SPACE)* CLOSE_NODE

word ::= named | list | val | element

val ::= QUOTE? VALUE QUOTE?

named ::= NAME ASSIGN (list | val)

list ::= val (LIST_SEPARATOR val)+
