{
  parserClass="org.logoce.lmf.editor.parser.LMParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="LMF"
  psiPackage="org.logoce.lmf.editor.psi"
  psiImplPackage="org.logoce.lmf.editor.psi.impl"

  elementTypeClass="org.logoce.lmf.editor.psi.LMElementType"
  tokenTypeClass="org.logoce.lmf.editor.psi.LMTokenType"
  elementTypeHolderClass="org.logoce.lmf.editor.psi.LMTokenTypes"

  tokens = [
    IDENTIFIER = 'regexp:[a-zA-Z_+\-=][a-zA-Z0-9_+\-=]*'
    WHITE_SPACE = 'regexp:\s+'
    OPEN_NODE = '('
    CLOSE_NODE = ')'
  ]
}

lmFile ::= list*

word ::= value | list

type ::= IDENTIFIER

value ::= IDENTIFIER

list ::= '(' type word* ')'
